config/routes.rb
Rails.application.routes.draw do
  resources :marcas
  resources :productos
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/marca.rb
class Marca < ApplicationRecord
	has_many :productos, dependent: :destroy
	validates :nombre, presence: true,
                    length: { minimum: 1 }
end

app/models/producto.rb
class Producto < ApplicationRecord
	 belongs_to :marca
	 validates :nombre, presence: true,
                    length: { minimum: 3 }
     validates :precio, :numericality => {:greater_than => 0, :less_than => 100}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/marcas_controller.rb
class MarcasController < ApplicationController
	def index
		@marca = Marca.all
	end
	def show
		redirect_to action: "index"
	end
	def new
		@marca = Marca.new
	end
	def edit
	  @marca = Marca.find(params[:id])

	end
	def create
		@marca = Marca.new(marca_params)
		if @marca.save
		redirect_to action: "index"
		else render 'new'
		end
	end
	def update
	  @marca = Marca.find(params[:id])
	
	  if @marca.update(marca_params)
		  	redirect_to action: "index"
	   else render 'edit' 
		end
	end

	def destroy
		@marca = Marca.find(params[:id])
		@marca.destroy
	    redirect_to action: "index"
 	 end


	private
	  def marca_params
	    params.require(:marca).permit(:nombre, :text)
	  end
	end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
	def index
		@producto = Producto.all
		@total = Producto.sum("precio")
	end
	def show
		redirect_to action: "index"
	end
	def new
		@producto = Producto.new
		@marca = Marca.all
	end
	def edit
	  @producto = Producto.find(params[:id])
	  @marca = Marca.all
	end
	def create
		@producto = Producto.new(producto_params)
		@marca = Marca.all
		if @producto.save
		redirect_to action: "index"
		else render 'new'
		end
	end 
	def update
	  @producto = Producto.find(params[:id])
	 
	  if @producto.update(producto_params)
	    redirect_to action: "index"
	  else
	  	@marca = Marca.all
	    render 'edit'
	  end
	end

	def destroy
	    @producto = Producto.find(params[:id])
	    @producto.destroy
	    redirect_to action: "index"
 	 end


	private
	  def producto_params
	    params.require(:producto).permit(:nombre, :marca_id, :descripcion, :precio)
	  end
	end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ejersicio</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="container" >
  <div class="col-md-8 col-md-offset-2">
     <img  src="/images/main.png" class="img-responsive img-circle centerImage" >
      	<nav class="navbar navbar-default">
      		<div class="container-fluid col-md-offset-3">
      			<div class="navbar-header ">
      				<a class="navbar-brand" href="https://github.com/Flanss/Catalogo_Productos"><span class="glyphicon glyphicon-cloud-download"></span></a>
      			</div>
      			<ul class="nav navbar-nav">
      				<li class="active"><li><%= link_to '|Inicio|', controller: 'welcome' %></li></li>
      				<li ><%= link_to '|Marcas|', controller: 'marcas' %></li>
      				<li ><%= link_to '|Productos|', controller: 'productos' %></li> 
      			</ul>
      		</div>
      	</nav>
    </div>
    </div>
   <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/marcas/edit.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2 well well-sm">
    <div class="row">
      <div class="col-md-3"><h5>Editar Marca</h5></div>
    </div>
   <%= form_for :marca, url: marca_path(@marca), :html => {:class => 'form-horizontal'}, method: :patch do |f| %>
    <% if @marca.errors.any? %>
    <div class="alert alert-danger col-md-4">
      <p>
        El nombre de la marca no puede estar vacio!.
      </p>
    </div>
    <% end %>
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="form-group">
          <%= f.label :Nombre %><br>
          <%= f.text_field :nombre, class: "form-control" %>
        </div>
      </div>
    </div>
    <input type="submit" class="btn btn-success pull-right" data-disable-with="Save Marca" value="Guardar" name="commit">
  </div>
  <% end %>
</div>

app/views/marcas/index.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2 well well-sm">
		<div class="row">
   			<div class="col-md-3"><h5>Lista de Marcas</h5></div>
  			 <div class="col-md-9"><%= link_to 'Nueva marca', new_marca_path, class: "btn btn-success btn-xs pull-right" %></div>
    	</div>
		<table class="table table-striped">
 		  <tr class="center">
		    <th>Nombre</th>
		    <th>Acciones</th>
		  </tr>
		 <% @marca.each do |marca| %>
		    <tr class="center">
		        <td><%= marca.nombre %></td>
		     	<td><%= link_to 'Editar', edit_marca_path(marca), class: "btn btn-primary btn-xs" %> <%= link_to 'Eliminar', marca_path(marca),class: "btn btn-danger btn-xs",
		              method: :delete,
		              data: { confirm: 'Estas seguro?, Tambien eliminaras todos los productos asociados' } %></td>
		    </tr>
		  <% end %>
		</table>
	</div>
</div>

app/views/marcas/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2 well well-sm">
    <div class="row">
      <div class="col-md-3"><h5>Nueva Marca</h5></div>
    </div>
    <%= form_for :marca, url: marcas_path, :html => {:class => 'form-horizontal'} do |f| %>
    <% if @marca.errors.any? %>
    <div class="alert alert-danger col-md-4">
      <p>
        El nombre de la marca no puede estar vacio!.
      </p>
    </div>
    <% end %>
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="form-group">
          <%= f.label :Nombre %><br>
          <%= f.text_field :nombre, class: "form-control" %>
        </div>
      </div>
    </div>
    <input type="submit" class="btn btn-success pull-right" data-disable-with="Save Marca" value="Guardar" name="commit">
  </div>
  <% end %>
</div>

app/views/marcas/show.html.erb
<p>
  <strong>index:</strong>

</p>

app/views/productos/edit.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2 well well-sm">
    <div class="row">
        <div class="col-md-3"><h5>Editar Producto</h5></div>
    </div>
      <%= form_for :producto, url: producto_path(@producto), :html => {:class => 'form-horizontal'}, method: :patch do |f| %>
    
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @producto.errors.full_messages.each do |msg| %>
         <div class="row">
     <div class="alert alert-danger col-md-4">
        <p>
          <%= msg %>
        </p>
      </div>
   </div>
         
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
       <div class="form-group">
          <%= f.label :Nombre %>
          <%= f.text_field :nombre, class: "form-control" %>
          <%= f.label :Marca %>
          <%= f.select :marca_id ,@marca.all.collect{|m| [m.nombre, m.id] },{}, {class: "form-control"}%>
     
          <%= f.label :Descripcion %>
          <%= f.text_field :descripcion, class: "form-control" %>
          <%= f.label :Precio %>
          <%= f.text_field :precio, class: "form-control" %>
       </div>
      </div>
      </div>
      <input type="submit" class="btn btn-success pull-right" data-disable-with="Save Marca" value="Guardar" name="commit">
  </div>
<% end %>
  </div>
</div>


app/views/productos/index.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2 well well-sm">
		<div class="row">
   			<div class="col-md-3"><h5>Lista de Productos</h5></div>
  			 <div class="col-md-9"><%= link_to 'Nuevo producto', new_producto_path, class: "btn btn-success btn-xs pull-right" %></div>
    	</div>
		<table class="table table-striped">
		  <tr class="center">
		    <th >Nombre</th>
		    <th >Marca</th>
		    <th >Descripcion</th>
		    <th >Precio</th>
		    <th >Acciones</th>
		  </tr> 
		  <% @producto.each do |producto| %>   
		    <tr class="center">

		        <td><%= producto.nombre %></td>
		     	<td><%= producto.marca.nombre %></td>
		     	<td><%= producto.descripcion %></td>
		     	<td><%= number_to_currency(producto.precio, :unit => "$") %></td>
		     	<td><%= link_to 'Editar', edit_producto_path(producto), class: "btn btn-primary btn-xs" %> <%= link_to 'Eliminar', producto_path(producto),class: "btn btn-danger btn-xs",
		              method: :delete,
		              data: { confirm: 'Estas seguro?' } %></td>
		    </tr>
		  <% end %>
		</table>
		<p class="pull-right"> Total: <%=number_to_currency(@total, :unit => "$") %></p>
	</div>
</div>

app/views/productos/new.html.erb

<div class="row">
  <div class="col-md-8 col-md-offset-2 well well-sm">
    <div class="row">
      <div class="col-md-3"><h5>Nuevo Producto</h5></div>
    </div>
    <%= form_for :producto, url: productos_path, :html => {:class => 'form-horizontal'} do |f| %>
    <% if @producto.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @producto.errors.full_messages.each do |msg| %>
        <div class="row">
          <div class="alert alert-danger col-md-4">
            <p>
              <%= msg %>
            </p>
          </div>
        </div>

        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="form-group">
          <%= f.label :Nombre %>
          <%= f.text_field :nombre, class: "form-control" %>
          <%= f.label :Marca %>
          <%= f.select :marca_id ,@marca.all.collect{|m| [m.nombre, m.id] },{}, {class: "form-control"}%>
          <%= f.label :Descripcion %>
          <%= f.text_field :descripcion, class: "form-control" %>
          <%= f.label :Precio %>
          <%= f.text_field :precio, class: "form-control" %>
        </div>
      </div>
    </div>
    <input type="submit" class="btn btn-success pull-right" data-disable-with="Save Marca" value="Guardar" name="commit">
  </div>
  <% end %>
</div>



app/views/productos/show.html.erb
<h1>Lista de Marcas</h1>


app/views/welcome/index.html.erb
<div class="col-md-8 col-md-offset-2 desc-text">
<img src="/images/power.png" class="centerImage" />
<p> Mi primera experiencia usando Ruby on Rails <span class="label label-primary">No Template!</span>, de lo que aprendí rails sirve para desarrollos rápidos escribiendo poco código y le brinda al desarrollador lo necesario para iniciar un proyecto, me parece chido el escribir poco código y a su vez hacer tantas cosas.</p>
<p>Con esta aplicación web aprendí como iniciar un proyecto básico, es probable que haya cosas bien echas o mal echas, pero quien sabe, fue desarrollada a mi criterio jeee.</p>
<p>Se ha de aprender mucho mas colaborando con mas personas, viendo sus diferentes formas de hacer las cosas, y tomar en cuenta sus puntos de vista.</p>
<p>Realizar algo como esto con el conocimiento de php me hubiese tardado un poco, mas sin embargo rails ofrece las herramientas necesarias para iniciar muy rápido, creo que los rails seniors pueden crear cosas con bastante facilidad ahorrando mucho tiempo.</p>
<p>Como seria trabajar en proyectos a modo colaborativo, y en proyectos grandes solo usando rails! .</p>
<p>Que aplicaciones tan enormes se podrían crear en rail! </p>
</div>